<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Iris Flower Dataset
</font>
</h1>

<h2 align=left style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
The Dataset</font>
</h2>

<p style="text-align: justify;line-height:200%;font-size:medium">
<a href="https://en.wikipedia.org/wiki/Iris_flower_data_set" target="_blank" style="color:#0099cc">Iris Flower dataset</a> includes the characteristics of 150 iris flowers. Each of these flowers belongs to one of the three types of iris: Iris setosa, Iris versicolor and Iris virginica. Also, the characteristics of each flower include the length and width of the sepal and petal. Using these characteristics, we can imagine each flower as a point in a four-dimensional space, where these four quantities determine the coordinates of that point.
</p>


<center>
<div style="max-width: 900px">
<img src="img/iris_types_en.png">
</div>
</center>

<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
The specifications of 120 iris flowers are stored in a file called <code>irises.npy</code>. When this file is read, a 120 x 4 array is created as shown in the figure below, each row of which shows the characteristics of a flower (sepal length, sepal width, petal length and petal width in cm).
</font>
</p>



<center>
<div style="max-width: 700px">
<img src="img/fig_irises.png">
</div>
</center>

In [1]:
import numpy as np

In [2]:
irises = np.load('irises.npy')
print(irises.shape)

(120, 4)



<p style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
On the other hand, the type of these flowers (setosa, versicolor, or virginica) is stored numerically in another file called <code>types.npy</code>. The values of this array are in the form of <code>0</code>، <code>1</code> and <code>2</code>, which represent the type of setosa iris, versicolor iris, and virginica iris, respectively.
</font>
</p>


In [3]:
types = np.load('types.npy')
print(types.shape)

(120,)


<p  style=";text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
In this project, I am going to implement an algorithm that will predict iris's type by receiving its characteristics. This prediction will be done with the help of samples which type we already know. These are the training data.
<br>
The specifications of 30 other iris flowers whose type we do not know and we are going to predict their type with the help of the k-NN algorithm are provided in another file called <code>new_irises.npz</code>. When this file is read, a 30 x 4 array is created as shown in the figure below, each row of which shows the characteristics of a flower. These are the test data.
</font>
</p>
<center>
<div style="max-width: 700px">
<img src="img/fig_new_irises.png">
</div>
</center>

In [4]:
new_irises = np.load('new_irises.npy')
print(new_irises.shape)

(30, 4)


<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Now let's call the number of training samples <code>n</code> and the number of test samples <code>m</code> and store them in variables with the same name.
</font>
</p>

In [5]:
n, m = len(irises), len(new_irises)
print("Number of training samples (n):", n)
print("Number of test samples (m):", m)

Number of training samples (n): 120
Number of test samples (m): 30


<h2 style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
KNN Algorithm</font>
</h2>

<p style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Suppose you are given the characteristics of a iris flower and you are supposed to recognize its type. Probably, the first idea that comes to your mind is to measure its similarity with flowers whose types you know and predict its type based on this similarity. Suppose you have found 3 flowers that are most similar to this flower. Now you know that out of these 3 flowers, for example, 2 are Virginia type flowers and 1 is setosa flower. You must also agree that according to the majority vote, it is more likely that our flower is of the Virginia type. So we declare this as our prediction.
<br>
This is exactly what the k-NN algorithm does. Of course, in this algorithm, instead of finding the greatest similarity, the smallest distance (difference) is usually calculated. The steps of this algorithm are as follows:
<ol>
<li>First, we calculate the distance of the test sample with all the training samples.</li>
<li>Then we find <code>k</code> training samples that have the smallest distance with our test sample.</li>
<li>Now we check which type these <code>k</code> samples mostly belonged to? We declare the same type as our prediction for the test instance.</li>
</ol>
</font>
</p>

<p style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Now let's start and implement each step of this algorithm with the help of numpy.
</font>
</p>

<h2   style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Part 1: Calculation of distances
</font>
</h2>

<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
First, we are going to code a function that calculates the distance of each of the samples/rows of an array such as <code>new_points</code> with each of the samples/rows of another array such as <code>points</code>. For example, if we have 120 training samples and 30 test samples, we must calculate the distance between each of the test samples and each of the training samples, so our output will have dimensions of 30 x 120. For example, the first row of this matrix, which is shown in the right figure below, includes the distance of the first test sample with each of the training samples.
</font>
</p>

<center>
<div style="max-width: 1000px">
<img src="img/fig.png">
</div>
</center>

<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
To calculate the distance between two points <code>p</code> and <code>q</code> with <code>f</code> feature, we will use the following formula:
</font>
</p>

$$ d(p,q) = {\sum_{i=0}^{f-1} (p_i - q_i)^2} $$

<p style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
In this example, <code>f</code> is equal to <code>4</code>. That is, to calculate the distance between two samples, it is enough to subtract the width of the sepals and multiply them to the power of 2, then do the same for the length of the sepals, the width of the petals, and the length of the petals and add the results for all four features together.
There are different methods to calculate the distance between the components of two arrays, and we will try 3 different approaches.
</font>
</p>.

<h3  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Two loops approach
</font>
</h3>


<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
First, we want to do this simply with the help of two <code>for</code> loops. In this method, we code a loop on the test samples and inside it we code a loop on the training samples so that for each test sample, the distance value with each of the training samples is calculated.
<br>
In the following function, we code an expression that calculates the distance between the two points <code>new_points[i]</code> and <code>points[j]</code> using the above formula.
<br>
</font>
</p>

In [6]:
def calc_two_loops(new_points, points):
    
    #‌ m is the number of new points (test samples)
    m = len(new_points)
    # n is the number of points (training samples)
    n = len(points)
    # Distance matrix
    d = np.zeros((m, n))
    
    # For each new point
    for i in range(m):
        # For each point
        for j in range(n):
            # Calculate the distance between the two points
            d[i, j] = np.sum(np.square(new_points[i] - points[j]))
            
    return d

In [7]:
d2 = calc_two_loops(new_irises, irises)
print(d2.shape)

(30, 120)


<h3  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
One loop approach
</font>
</h3>


<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Now we want to use the broadcasting and rearranging feature of the arrays and remove each of the loops respectively. In this part, we want to remove the inner loop and calculate the distance of each test sample simultaneously with all the training samples with the help of the broadcasting feature of the array. So, in the following function,we'll write a block of code that calculates the distance between all the training samples and the test sample <code>new_points[i]</code>.
<br>
</font>
</p>

In [8]:
def calc_one_loop(new_points, points):
    
    #‌ m is the number of new points (test samples)
    m = len(new_points)
    # n is the number of points (training samples)
    n = len(points)
    # Distance matrix
    d = np.zeros((m, n))
    
    # For each new point
    for i in range(m):
        # Calculate the distance between the new point and all the points
        d[i] = np.sum(np.square(new_points[i] - points), axis=1)
        
    return d

In [9]:
d1 = calc_one_loop(new_irises, irises)
print(d1.shape)

(30, 120)


<h3  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
No loops approach
</font>
</h3>


<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Again, we use the properties of arrays and write only one line of code in the following function to output all the spaces.
<br>
It may seem complicated to construct an array of intervals without a loop. But using numpy functions instead of loop makes the code both faster and shorter.
</font>
</p>

In [10]:
def calc_no_loop(new_points, points):
    return np.sum(np.square(new_points), axis=1).reshape(-1, 1) + np.sum(np.square(points), axis=1) - 2 * np.matmul(new_points, points.T)        

In [11]:
d = calc_no_loop(new_irises, irises)
print(d.shape)

(30, 120)


<h3 style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Making Sure it works!
🧐
</font>
</h3>

<p style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Calculating the distance array in the above three ways should not make any difference in the result. Therefore, we run the following code to make sure that the output of the above three functions is equal. From now on, we will use the <code>d</code> array as the distance array.
</font>
</p>

In [12]:
if np.allclose(d, d1, 1e-5) and np.allclose(d, d2, 1e-5) and np.allclose(d1, d2, 1e-5):
    print('Fine!')
else:
    print('There is something wrong!')

Fine!


<h2  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Finding nearest neighbor
</font>
</h2>

<p style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
With the help of the implemented functions, we were able to calculate the distance of each test sample with each of the training samples and stored the result in <code>d</code>.
     So, we have stored the distance between the test sample <code>new_irises[i]</code> and the training sample <code>irises[j]</code> in <code>d[i][j]</code>. Now, for each test sample, we need to find <code>k</code> training samples with the smallest distance to it. Note that we need to store the number of closest samples, not the distance value itself. Here, consider <code>k</code> equal to <code>10</code>, so the output array <code>k_nearest</code> will be a matrix of dimensions <code dir=ltr>(30, 10)</code>.
</font>
</p>

In [13]:
k = 10
k_nearest = np.argpartition(d1, k, axis=1)[:, :k]
print(k_nearest)

[[  6  14   0  32  22  17  39  21  23  37]
 [ 10   1  30  24  20   2  36   3   6  28]
 [ 27  13   8  39   4  29  15  12  26  25]
 [ 14  17   0  39  37  22   8  32  26  13]
 [ 21  20  30   3   9  24   6  19  35   5]
 [ 10   1   2   3  38   5  36  30  24   9]
 [ 10   1  30  24  20   2  36   3   6  28]
 [  0   6  22  23  21  14   9  32  17  39]
 [ 39  35  17  22   4  21  37  19   8  16]
 [ 28   6  23   0  14  21  30  32  22   9]
 [ 47  73  69  61  52  51  41  60 101  58]
 [ 71  43  65  64  77  72  66  76  74  54]
 [ 71  65  74  64  66  77  76  54  57  49]
 [ 64  65  74  66  43  50  54  72  77  71]
 [ 78  60  47  41  73  52  63  57  51  59]
 [ 74  65  54  64  66  43  50  57  71  75]
 [ 77  71  44  53  72  76  49  97  56  63]
 [ 72  66  64  74  43  65  77  54  71  76]
 [ 77  74  44  72  71  76  54  66  43  53]
 [ 66  54  71  76  77  74  49  57  44  72]
 [ 90 103 106  96 112 115  93 110  83  80]
 [ 82  96 100 108  94 115 112 105  80  84]
 [111  92  97 117  81 114 102  91 101  56]
 [107  67  

<h2  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Finding K nearest type
</font>
</h2>

<p style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Now we have the index of the nearest neighbors (training samples) for each test sample in the <code>k_nearest</code> array. But we are looking for the type of each of them. In order to replace the type of that flower instead of each index, we can use the <code>types</code> array. We do this in one line and value the ‌<code>k_nearest_types</code> variable.
</font>
</p>

In [14]:
k_nearest_types = types[k_nearest]
k_nearest_types

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 2, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [2, 1, 2, 2, 1, 2, 2, 2, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2,

<h2  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Predicting new irises
</font>
</h2>

<p  style="text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
Finally, we need to create an array named <code>predicted_types</code> of length <code>m</code>, where in <code>predicted_types[i]</code> the most frequent identifier in <code>k_nearest_types[i]</code> is placed as the predicted type identifier for <code>new_irises[i]</code>.
     <br>
     Since numpy doesn't directly have the (<code>mode</code>) function, we have done this with the help of the <code>mode</code> function that is inside the <code>scipy</code> library.
</font>
</p>

In [15]:
from scipy import stats
predicted_types = stats.mode(k_nearest_types, axis=1).mode.reshape(m)
predicted_types

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)